# Generated by Django 2.2.9 on 2020-02-02 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('pages', '0010_formfield_formpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='hero_caption',
            field=models.CharField(blank=True, help_text='140 character limit.', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='hero_cta',
            field=models.CharField(blank=True, help_text='Text to display on Call to Action. 20 character limit.', max_length=20, null=True, verbose_name='Hero CTA'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='hero_cta_link',
            field=models.ForeignKey(blank=True, help_text='Choose a page to link the Call to Action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Hero CTA link'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='hero_heading',
            field=models.CharField(blank=True, help_text='40 character limit.', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='2400X858px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='hero_photo_credit',
            field=models.CharField(blank=True, help_text='80 character limit. This will show on the bottom right on the image', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='hero_photo_credit_link',
            field=models.URLField(blank=True, help_text='If you would like the above text to link to a website. Enter complete URL here.', null=True),
        ),
    ]
