# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20171015_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trusteespage',
            old_name='trustee',
            new_name='directory',
        ),
    ]
