# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 13:54
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20171016_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='image',
            field=wagtail.wagtailcore.fields.StreamField((('hero_image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True)), ('alternate_text', wagtail.wagtailcore.blocks.CharBlock(help_text='Text for screen readers')), ('caption', wagtail.wagtailcore.blocks.CharBlock(help_text='Caption will be shown below the image', max_length=120, required=False)), ('fine_print', wagtail.wagtailcore.blocks.CharBlock(help_text='Fine Print will be shown below caption', max_length=120, required=False)), ('overlay_text', wagtail.wagtailcore.blocks.BooleanBlock(help_text='If checked, caption is overlayed on image', required=False)), ('photo_credit', wagtail.wagtailcore.blocks.CharBlock(help_text='This will show bottom right on the image', max_length=80, required=False))), icon='image')),), default=''),
        ),
    ]
