# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_formpage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formpage',
            old_name='image',
            new_name='body',
        ),
    ]
